- name: Adding Docker Repo Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Adding Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ubuntu_dist }} stable
    state: present

- name: Installing Docker Dependencies
  ansible.builtin.apt:
    state: latest
    update_cache: true
    allow_downgrade: true
    lock_timeout: 120
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Installing Docker Packages
  ansible.builtin.apt:
    state: latest
    update_cache: true
    allow_downgrade: true
    lock_timeout: 120
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  notify: Restart Docker Service
