- name: Setup Users
  block:
    - name: Modify User
      ansible.builtin.user:
        name: "{{ user }}"
        uid: "{{ uid }}"
        umask: u=rwx,g=,o=
        groups: "{{ item }}"
        create_home: true
        shell: /usr/bin/zsh
        password: "{{ password | password_hash('sha512', password_salt) }}"
        append: true
      loop:
        - sudo
        - docker
        - video

    - name: Copying Public SSH Key
      ansible.posix.authorized_key:
        follow: true
        user: "{{ item }}"
        key: "{{ lookup('file', lookup('ansible.builtin.env', 'HOME') + '/.ssh/' + pub_ssh_key) }}"
        state: present
      loop:
        - "{{ user }}"
        - root
